// The states that actually appear in the 1978 poster, found by matching each
// of its 63 tiles against the edition. Items carrying one of these keys get
// the trait Provenance: 'Malcolm Garrett 1978'.
// Generated by scripts/provenance.mjs - do not edit by hand.
export const IN_POSTER = new Set([
 "0|false|BUZZCOCKS|B|standard",
 "0|false|DO|B|standard",
 "0|false|GET?|B|standard",
 "0|false|I|B|standard",
 "0|false|UP 36348|B|standard",
 "0|false|WHAT|B|standard",
 "0|true|DO|B|standard",
 "0|true|GET?|B|standard",
 "0|true|UP 36348|B|standard",
 "1|false|BUZZCOCKS|B|standard",
 "1|false|DO|A|standard",
 "1|false|GET?|B|standard",
 "1|false|I|B|standard",
 "1|false|UP 36348|B|standard",
 "1|false|WHAT|B|red",
 "1|false|WHAT|B|standard",
 "1|true|GET?|A|standard",
 "1|true|I|B|standard",
 "1|true|UP 36348|B|red",
 "1|true|WHAT|B|standard",
 "2|false|GET?|B|red",
 "2|false|UP 36348|B|standard",
 "2|false|WHAT|B|standard",
 "2|true|BUZZCOCKS|B|red",
 "2|true|DO|A|standard",
 "2|true|GET?|B|standard",
 "2|true|WHAT|B|standard",
 "3|false|DO|B|standard",
 "3|false|I|B|standard",
 "3|false|UP 36348|B|standard",
 "3|false|WHAT|B|standard",
 "3|true|BUZZCOCKS|B|standard",
 "3|true|GET?|B|standard",
 "3|true|UP 36348|B|standard",
 "3|true|WHAT|B|standard"
]);

// The same states as objects, so the edition can issue them deliberately
// rather than leaving them to a shuffle.
export const POSTER_STATES = [
 {
  "rot": 3,
  "mirror": true,
  "word": "UP 36348",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 2,
  "mirror": true,
  "word": "GET?",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 1,
  "mirror": false,
  "word": "BUZZCOCKS",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 0,
  "mirror": false,
  "word": "WHAT",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 2,
  "mirror": true,
  "word": "DO",
  "plane": "A",
  "plate": "standard"
 },
 {
  "rot": 3,
  "mirror": false,
  "word": "WHAT",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 0,
  "mirror": false,
  "word": "BUZZCOCKS",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 1,
  "mirror": true,
  "word": "GET?",
  "plane": "A",
  "plate": "standard"
 },
 {
  "rot": 0,
  "mirror": false,
  "word": "I",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 1,
  "mirror": true,
  "word": "UP 36348",
  "plane": "B",
  "plate": "red"
 },
 {
  "rot": 2,
  "mirror": true,
  "word": "BUZZCOCKS",
  "plane": "B",
  "plate": "red"
 },
 {
  "rot": 3,
  "mirror": true,
  "word": "WHAT",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 0,
  "mirror": false,
  "word": "DO",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 1,
  "mirror": true,
  "word": "I",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 1,
  "mirror": false,
  "word": "UP 36348",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 1,
  "mirror": false,
  "word": "WHAT",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 3,
  "mirror": true,
  "word": "BUZZCOCKS",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 0,
  "mirror": false,
  "word": "GET?",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 3,
  "mirror": false,
  "word": "UP 36348",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 2,
  "mirror": true,
  "word": "WHAT",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 1,
  "mirror": false,
  "word": "GET?",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 1,
  "mirror": true,
  "word": "WHAT",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 1,
  "mirror": false,
  "word": "DO",
  "plane": "A",
  "plate": "standard"
 },
 {
  "rot": 2,
  "mirror": false,
  "word": "UP 36348",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 3,
  "mirror": true,
  "word": "GET?",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 2,
  "mirror": false,
  "word": "WHAT",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 3,
  "mirror": false,
  "word": "DO",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 0,
  "mirror": false,
  "word": "UP 36348",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 1,
  "mirror": false,
  "word": "I",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 0,
  "mirror": true,
  "word": "UP 36348",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 2,
  "mirror": false,
  "word": "GET?",
  "plane": "B",
  "plate": "red"
 },
 {
  "rot": 1,
  "mirror": false,
  "word": "WHAT",
  "plane": "B",
  "plate": "red"
 },
 {
  "rot": 3,
  "mirror": false,
  "word": "I",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 0,
  "mirror": true,
  "word": "DO",
  "plane": "B",
  "plate": "standard"
 },
 {
  "rot": 0,
  "mirror": true,
  "word": "GET?",
  "plane": "B",
  "plate": "standard"
 }
];
